version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P12345p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet
  myapp:
    image: fatihtepe/bookstoreapi:latest
    container_name: mayapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - clarusnet
networks:
  clarusnet:
    driver: bridge



